site_name: My Docs
project_name : Juice
repo_url: https://github.com/Dxtan/mkdocs-juice
site_author: Dxtan
copyright: Copyright Â© 2016 Dxtan, Mkdocs Juice.
theme_dir: theme
# Add permalink for sharing
markdown_extensions:
    - smarty
    - toc:
#        permalink: True
    - sane_lists

pages:
  - Home : 'index.html'
  - QuickStart : 'QuickStart.md'


