site_name: My Docs
pages:
- HOME: 'index.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release.md'
theme_dir: theme

# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
